---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На странице товара и в каталоге отображается название, рейтинг, цена со скидкой и без нее
  - При переходе по страницам каталога, страница не перезагружается
  - Пользователь должен иметь возможность удалить товар из корзины на странице корзины
  - Пользователь должен иметь возможность на странице корзины оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность произвести оплату заказанных товаров
